### Método POST para Generar un Archivo Excel

##Este método POST permite generar un archivo Excel basado en los datos proporcionados en el cuerpo de la solicitud. Utiliza la clase `ExcelHandler` para crear archivos Excel con hojas de trabajo personalizables, encabezados y datos.

#### Datos de Solicitud

##El cuerpo de la solicitud debe contener un objeto JSON con la siguiente estructura:

POST http://localhost:1080/read/excel
Content-Type: application/json

{
  "filePath": "static/test.xlsx",
   "type": "xlsx",
   "validations": {
      "columns": [
         {
            "sheet": "Hoja1",
            "items": [
               {
                  "key": "Nombre",
                  "type": "string"
               },
               {
               "key": "Edad",
               "type": "number"
               }  
            ]
         }  
      ]
   }
}

