### Método POST para Generar un Archivo Excel

##Este método POST permite generar un archivo Excel basado en los datos proporcionados en el cuerpo de la solicitud. Utiliza la clase `ExcelHandler` para crear archivos Excel con hojas de trabajo personalizables, encabezados y datos.

#### Datos de Solicitud

##El cuerpo de la solicitud debe contener un objeto JSON con la siguiente estructura:
POST http://localhost:1080/generate/excel
Content-Type: application/json

{
   "sheetData":[
      {
         "sheetName":"Hoja1",
         "columnsHeader":[
            {
               "header":"Nombre",
               "key":"name"
            },
            {
               "header":"Edad",
               "key":"age"
            }
         ],
         "data":[
            {
               "name":"Juan",
               "age":25
            },
            {
               "name":"María",
               "age":30
            }
         ]
      },
      {
         "sheetName":"Hoja2",
         "columnsHeader":[
            {
               "header":"Producto",
               "key":"product"
            },
            {
               "header":"Precio",
               "key":"price"
            }
         ],
         "data":[
            {
               "product":"Producto A",
               "price":10
            },
            {
               "product":"Producto B",
               "price":15
            }
         ]
      }
   ],
   "filename": "test.xlsx"
}
